#-------------------nakashima 2015/12/08 edited------------------------#
DSAE_PBHL: Deep_Sparse_Autoencoder.cpp
	mkdir -p DSAE_PBHL
	cp setting.txt sample5D_data.txt DSAE_PBHL/
	g++ -Ofast -Os -w Deep_Sparse_Autoencoder.cpp -o DSAE_PBHL/DSAE_PBHL.exe #Optimization Option
	#g++ Deep_Sparse_Autoencoder.cpp -o DeepSparseAutoencoder/DeepSparseAutoencoder.exe
